services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"    # Porta AMQP para conexões RabbitMQ
      - "15672:15672"  # Porta da interface web de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: rabbitmq_rpc_server
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_RPC=fila_rpc
    networks:
      - rabbitmq_network
    volumes:
      - ./server:/data

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
